openapi: 3.0.1
info:
  title: SendMessageAPI
  version: 1.0
paths:
  /messages:
    post:
      summary: Invia un messaggio alla coda
      responses:
        '200':
          description: Messaggio inviato con successo
        '404':
          description: Messaggio non trovato
        default: Errore generico
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sendMessageSchema'
      x-amazon-apigateway-integration:
        type: "aws"
        httpMethod: POST
        responses:
          default:
            statusCode: 200
        uri: 
          Fn::Sub:
            - "arn:aws:apigateway:${AWS::Region}:sqs:path/${AWS::AccountId}/${QueueName}"
            - QueueName: { 'Fn::GetAtt': [ MessageQueue, QueueName ] }
        credentials: { 'Fn::GetAtt': [SQSRole, Arn] }
        passthroughBehavior: WHEN_NO_MATCH
        requestParameters:
          integration.request.header.Content-Type: "'application/x-www-form-urlencoded'"
        requestTemplates:
          application/json: Action=SendMessage&MessageBody=$util.escapeJavaScript($input.body).replaceAll("\\'","'")
components:
  schemas:
    sendMessageSchema:
      type: object
      properties:
        val1:
          type: number
        val2:
          type: number